React Capstone project - Metrics webapp: Milestone Completion
vanina123/react-capstone pull request #1
Opened 2023-06-02 20:55 UTC by vanina123

- Use React documentation.
- Use React components.
- Use React props.
- Use React Router.
- Connect React and Redux.
- Handle events in a React app.
- Write integration tests with a React testing library.
- Use styles in a React app.
- Use React life cycle methods.
- Apply React best practices and language style guides in code.
- Use store, actions and reducers in React.

2023-06-02 21:47 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @vanina123👋, 

### You are doing a marvelous job on the React capstone project and this is one of the best projects I have seen so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![image](https://github.com/vanina123/react-capstone/assets/83803414/d4e904e3-4f02-47bf-a750-bce2efc93618)

## To Highlight 🎉
- All tests are passed. ✔️
- No linter errors. :heavy_check_mark:
- Highly organized code. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Please make sure to record a video presenting the features of the project you built and add the video link in the PR description as requested in the project requirements. It is a video with a maximum length of 5 minutes. The content of the video should include:
  - Description of the project.
  - Demo of the project features.
  - You should also highlight some interesting piece of code or something you built that you are very proud of.

- [ ] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-02 21:47 UTC, thecodechaser commented on src/components/homePage.js
> +
- [ ] You did great on the project but you need to fix the below design issues to follow the given design.
  - Please make sure to display two items(star wars characters) in a row as on the design. Currently, there's one item displayed in a row.

### Your design

![image](https://github.com/vanina123/react-capstone/assets/83803414/49ed1ebd-c296-46bf-89cf-9e57bd1d888e)

### Given design

![image](https://github.com/vanina123/react-capstone/assets/83803414/893cc7dc-8567-412f-9e71-a3b1aacaf7e2)

2023-06-03 13:09 UTC, fobadara requested changes
Hi @vanina123, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Implemented reviewer suggestions
✅ Nice design

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 13:09 UTC, fobadara commented on src/components/homePage.js
> -                  {character.status}
[REQUIRED] Good job dividing the cards into two sections but in order for your design to look more like the template we you need to remove the spaces between and at the side of the cards.

![image](https://github.com/vanina123/react-capstone/assets/62938735/72603e1a-a29b-4924-8cba-806455111f0f)

2023-06-03 16:13 UTC, shella12 approved these changes
Hi @vanina123, 


## Status : APPROVED 🥳 🥳 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

## Highlights

- Great design implementation ✔️ 
- Great app 👍 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 16:24 UTC, merged